# Generated by Django 5.0.4 on 2024-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('message', models.TextField(max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
